version: '3'
services:
  nginx:
    image: nginx:${NGNIX_VERSION}
    depends_on:
      - client
      - admin
    links:
      - client:client
      - admin:admin
      - backend:backend
    restart: on-failure:30
    volumes:
      - ./deploy/shared/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env
    networks:
      - default
    expose:
      - 80
    ports:
      - ${NGINX_BIND_PORT}:80
  mongo:
    image: mongo:${MONGO_VERSION}
    env_file:
      - .env
    networks:
      - default
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  client:
    build:
      context: .
      target: client
    networks:
      - default
    volumes:
    - ./src/client:/usr/src/app
  admin:
    build:
      context: .
      target: admin
    networks:
      - default
    volumes:
    - ./src/admin:/usr/src/app
  backend:
    build:
      context: .
      target: backend
    networks:
      - default
    volumes:
    - ./src/app:/usr/src/app
    ports:
    - 5000:5000

networks:
  default:
    driver: bridge
